# Generated by Django 5.2.8 on 2025-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='campaignupdate',
            old_name='content',
            new_name='content_md',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignupdate',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='campaignupdate',
            name='title',
            field=models.CharField(default='# Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.tag'),
        ),
    ]
