# Generated by GitHub Copilot on 2026-01-05

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
    ("campaigns", "0002_tag_rename_content_campaignupdate_content_md_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="campaign",
      name="donate_qr_image_url",
      field=models.URLField(blank=True),
    ),
  ]
