# Generated by Django 5.2.8 on 2025-12-29 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorgroup',
            name='join_code',
        ),
    ]
