# Generated by GitHub Copilot on 2026-01-05

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  dependencies = [
    ("groups", "0003_donorgroup_image_url"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="GroupMessage",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("content", models.TextField()),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "group",
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="groups.donorgroup"),
        ),
        (
          "sender",
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_messages", to=settings.AUTH_USER_MODEL),
        ),
      ],
      options={"ordering": ["-created_at"]},
    ),
    migrations.CreateModel(
      name="GroupMessageReadState",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("last_read_message_id", models.BigIntegerField(default=0)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "group",
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="message_reads", to="groups.donorgroup"),
        ),
        (
          "user",
          models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="group_message_reads", to=settings.AUTH_USER_MODEL),
        ),
      ],
      options={"unique_together": {("group", "user")}},
    ),
  ]
