# Generated by GitHub Copilot on 2025-12-29
# Modified by Gemini to fix DuplicateColumn error on fresh deployments

from __future__ import annotations

from django.db import migrations, models


def add_phone_column_if_missing(apps, schema_editor):
    # Get the model from the versioned app registry
    Profile = apps.get_model("user", "Profile")
    db_table = Profile._meta.db_table
    
    # Use the connection from the schema_editor
    connection = schema_editor.connection
    
    # Introspect the database to check for the column
    with connection.cursor() as cursor:
        description = connection.introspection.get_table_description(cursor, db_table)
        existing_columns = [col.name for col in description]
    
    if "phone" not in existing_columns:
        # Get the field definition from the model
        field = Profile._meta.get_field("phone")
        # Ensure we have a default for the column addition, matching the original SQL intent
        field.default = ""
        # Add the field
        schema_editor.add_field(Profile, field)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # The initial migration file was edited after being applied on an
            # existing SQLite DB, so the DB schema may be missing the phone column.
            # Keep Django's migration state unchanged (it already has `phone`) and
            # patch the database schema only.
            database_operations=[
                migrations.RunPython(
                    code=add_phone_column_if_missing,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="profile",
                    name="phone",
                    field=models.CharField(default="", max_length=30),
                ),
            ],
        ),
    ]