# Generated by GitHub Copilot on 2025-12-29

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # The initial migration file was edited after being applied on an
            # existing SQLite DB, so the DB schema may be missing the phone column.
            # Keep Django's migration state unchanged (it already has `phone`) and
            # patch the database schema only.
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE user_profile ADD COLUMN phone varchar(30) NOT NULL DEFAULT ''",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="profile",
                    name="phone",
                    field=models.CharField(default="", max_length=30),
                ),
            ],
        ),
    ]
