# Generated by GitHub Copilot on 2026-01-03

from __future__ import annotations

from django.db import migrations


def drop_opt_in_pairing_column(apps, schema_editor):
    """Remove legacy NOT NULL column `opt_in_pairing` from `user_profile`.

    This project previously had a pairing feature; some SQLite databases may still
    contain a `user_profile.opt_in_pairing` column with a NOT NULL constraint.
    Since the field no longer exists in the Django model state, inserts can fail
    with: NOT NULL constraint failed: user_profile.opt_in_pairing.

    SQLite doesn't support dropping a column directly in older versions, so we
    rebuild the table.
    """

    if schema_editor.connection.vendor != "sqlite":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(user_profile)")
        columns = [row[1] for row in cursor.fetchall()]

    if "opt_in_pairing" not in columns:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA foreign_keys=OFF;")

        # Recreate the table with the current model schema.
        cursor.execute(
            """
            CREATE TABLE user_profile__new (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                can_fundraise bool NOT NULL,
                phone varchar(30) NOT NULL DEFAULT '',
                created_at datetime NOT NULL,
                user_id integer NOT NULL UNIQUE
                    REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED
            );
            """
        )

        # Copy over existing data, ignoring the legacy column.
        cursor.execute(
            """
            INSERT INTO user_profile__new (id, can_fundraise, phone, created_at, user_id)
            SELECT
                id,
                can_fundraise,
                COALESCE(phone, ''),
                created_at,
                user_id
            FROM user_profile;
            """
        )

        cursor.execute("DROP TABLE user_profile;")
        cursor.execute("ALTER TABLE user_profile__new RENAME TO user_profile;")
        cursor.execute("PRAGMA foreign_keys=ON;")


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_phone_db_fix"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_opt_in_pairing_column,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[],
        ),
    ]
