# Generated by GitHub Copilot on 2026-01-03

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_drop_profile_opt_in_pairing_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
