# Generated by GitHub Copilot on 2026-01-05

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		("groups", "0003_donorgroup_image_url"),
		("user", "0004_profile_extra_fields"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="Notification",
			fields=[
				("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
				("kind", models.CharField(choices=[("group_added", "Group added"), ("donation", "Donation"), ("group_messages", "Group messages")], max_length=40)),
				("message", models.TextField()),
				("url", models.CharField(blank=True, default="", max_length=300)),
				("is_read", models.BooleanField(default=False)),
				("created_at", models.DateTimeField(auto_now_add=True)),
				(
					"group",
					models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="groups.donorgroup"),
				),
				(
					"user",
					models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL),
				),
			],
			options={"ordering": ["-created_at"]},
		),
	]
