# Generated by Django 5.2.8 on 2026-01-03 09:36

import django.db.models.deletion
import donor_groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('group_code', models.CharField(default=donor_groups.models.generate_group_code, help_text='Unique code for joining this group', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Group',
                'verbose_name_plural': 'Donor Groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='donor_groups.donorgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donor Group Membership',
                'verbose_name_plural': 'Donor Group Memberships',
                'ordering': ['joined_at'],
                'unique_together': {('group', 'member')},
            },
        ),
    ]
